### ISSUE TITLE
Fix 7.8, 7.6 builds

### ISSUE THREAD

**Issue by dmjio** [haskell-miso/miso#181]
Builds failing here, due to `base` being pre-AMP.
https://matrix.hackage.haskell.org/package/miso#GHC-7.8/miso-0.1.5.0

**Comment by FintanH** [comment]
Sorry I'm a bit ignorant as to how to approach fixing this issue. I'd love to help out if you can help me out as to how to start replicating the issue then fixing it :)

**Comment by dmjio** [comment]
Hey @FintanH, thanks for getting in touch. I saw this issue made it into the CFP. Think it might be best to tackle this one lazily and just wait until someone actually complains about `7.8` (or pre) support (almost 100% chance no one will) -- but someone did complain about Windows support, so who knows. I think your time might be better served in working on `miso-from-html` (https://github.com/dmjio/miso/issues/198) (if interested). It would be immensely helpful for all users, and help me as I finish https://haskell-miso.org. Right now this is what I have so far: https://github.com/dmjio/miso/issues/198. It's pretty straightforward Haskell. A similar, but more involved project would be `blaze-from-html`. You could convert the `HTML` -> `Blaze` -> `Miso`, but honestly, `tagsoup` (as shown in the gist on https://github.com/dmjio/miso/issues/198), might be enough. If you can make `miso-from-html` generate Haskell code (as a `String` is fine), that ghc can compile, that'd be great.

**Comment by dmjio** [comment]
cc @alexeyzab

**Comment by dmjio** [comment]
We're dropping `7.8` support. Similar to `llvm-hs`. https://github.com/llvm-hs/llvm-hs/issues/125
