### ISSUE TITLE
Make Flatris example

### ISSUE THREAD

**Issue by dmjio** [haskell-miso/miso#204]
This would be neat to make. https://github.com/w0rm/elm-flatris

**Comment by ptigwe** [comment]
I have been working on this for the past few days and currently, have a working example of this which is available at https://github.com/ptigwe/hs-flatris

**Comment by dmjio** [comment]
Wow, you're awesome. Fantastic work. I'd like to include this as an example in the main source. The closer we can get it to look like `elm-flatris` the better. Will check it out more tonight. I've fixed some issues around `Miso.String` (obviating the need for `ExtendedDefaultRules`) and excessive calls to `pack` in `miso-0.6.0.0`, so feel free to upgrade. Again, thank you.

**Comment by ptigwe** [comment]
Brilliant. I'll upgrade to the most recent version and make the necessary changes.

One of the issues which I faced when implementing this was the use of elm's AnimationFrame package. Currently, I've given each action (rotation, movement and drop) their own individual frame counters as a way around this.

**Comment by dmjio** [comment]
This is beautiful work. **Exactly** what I'd hoped this example would look like. Bravo.

Also, the model being updated in real time is a cherry on top.

I'd be interested in knowing more about what you encountered with Elm's `animationFrame` package. The animation frame code was the part at which the miso `mario` example diverged from the Elm `mario`.

One thing undocumented (but it seems you figured out just fine) is that a new animation frame is requested when the model has changed. So by saving ticks to the model, you're ensuring a new frame will always be called. The `mario` example takes a similar approach. 

Individual frame counters is an approach that might be worth adding to the documentation for others who'd like to make games. I'm also curious to know more about this approach :)

Please do update to `0.6` and make a `PR`, and we can get this hosted on Amazon's CDN with the list of other public examples. Great work 🍻

**Comment by dmjio** [comment]
https://flatris.haskell-miso.org/, will update it to `0.6` when your PR comes in :)

**Comment by mstksg** [comment]
this is beautiful

**Comment by dmjio** [comment]
@ptigwe, if you'd like instead, we could keep the source at your [repo location](https://github.com/ptigwe/hs-flatris) (since there are quite a few modules), and just add a link on the `miso` README to your source and a link to https://flatris.haskell-miso.org. How does this sound? Do advise.

**Comment by dmjio** [comment]
https://github.com/haskell-miso/miso/pull/251

**Comment by dmjio** [comment]
@ptigwe I've also added `flatris` to the list of examples here: https://haskell-miso.org/examples

**Comment by ptigwe** [comment]
@dmijo This sounds good to me. I believe the examples maintained in the main repo should be limited to single file bite size pieces. Longer apps can be linked to from the README file.

**Comment by dmjio** [comment]
Great work :) and thanks. Closing since finished.
