### ISSUE TITLE
Move to gitter

### ISSUE THREAD

**Issue by dmjio** [haskell-miso/miso#230]
cc @fizruk @cocreature @nickseagull

**Comment by cocreature** [comment]
Just as I’ve gotten used to slack instead of IRC ;) Just kidding, I don’t have a strong opinion on this so I’m fine with moving.

**Comment by srid** [comment]
The functionalprogramming Slack community could be a home, with #miso being a new channel there (in addition to things like #purescript #ghcjs #haskell etc..)?

**Comment by dmjio** [comment]
@srid that sounds fine as well.

**Comment by srid** [comment]
@dmjio I created a `#miso` channel over there. Users can join using this link: https://fpchat-invite.herokuapp.com/

Slack or Gitter ... I feel it would be nice to have a chat community sooner than later.

**Comment by dmjio** [comment]
@srid thanks, we do currently have https://haskell-miso-slack.herokuapp.com/ and #haskell-miso IRC, but the more the merrier

**Comment by cocreature** [comment]
I’m not sure I agree with “the more the merrier” in this case. Splitting the communication of the currently relatively small group of miso users over several channels only makes it confusing for users where they should go.

**Comment by dmjio** [comment]
@cocreature fair enough, let's just stay on slack for now. Will reopen for serious objections.
