### ISSUE TITLE
nixos: How to use the latest version of miso?

### ISSUE THREAD

**Issue by srid** [haskell-miso/miso#236]
I followed the README but nix only installs an older version (0.4.0.0) of miso. I think this is because the nix package store is not in sync with hackage. So I had to use the example mentioned in the README of 0.4.0.0. 

How do I use the latest miso which is 0.6.0.0 when using nix?

**Comment by dmjio** [comment]
Ah, assuming you have followed the nix instructions on the `README.md` it appears that the `rev` is pointing to an old version of `miso`. I made an updated version and tar'd it up here: https://www.dropbox.com/s/6k53iz8f8031ltx/app.tgz?dl=0

You can `cd` into it and call `nix-build` or `nix-shell -A env && cabal configure --ghcjs`.

It has the following files in it:

`Main.hs`
```haskell
module Main where

import Miso

main :: IO ()
main = putStrLn "foo"
```
`app.cabal`
```
name:                app
version:             0.1.0.0
synopsis:            First miso app
category:            Web
build-type:          Simple
cabal-version:       >=1.10

executable app
  main-is:             Main.hs
  build-depends:       base, miso
  default-language:    Haskell2010
```
`app.nix`
```nix
{ mkDerivation, base, miso, stdenv }:
mkDerivation {
  pname = "app";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [ base miso ];
  description = "First miso app";
  license = stdenv.lib.licenses.unfree;
}
```
`default.nix`
```nix
{ pkgs ? import <nixpkgs> {} }:
let
  result = import (pkgs.fetchFromGitHub {
    owner = "dmjio";
    repo = "miso";
    sha256 = "07v2wrinnvkcmrmrav5xngybbms4scqhrhprbfqyak20snr4ir1q";
    rev = "e2a3ac05f6b228c6060046fbdbf3d93c4232229c";
  }) {};
in pkgs.haskell.packages.ghcjs.callPackage ./app.nix {
  miso = result.miso-ghcjs;
}
```

Let me know if this has helped.

**Comment by srid** [comment]
```
sha256 = "07v2wrinnvkcmrmrav5xngybbms4scqhrhprbfqyak20snr4ir1q";
rev = "e2a3ac05f6b228c6060046fbdbf3d93c4232229c";
```

Updating just these two lines successfully pulled versioin 0.6.0.0 during nix-build however the sample program mentioned in the README is failing to build. The source tree is here: https://github.com/srid/miso-hello

```
Main.hs:44:38:
    Couldn't match type ‘[Char]’ with ‘JSString’
    Expected type: MisoString
      Actual type: [Char]
    In the first argument of ‘text’, namely ‘"+"’
    In the expression: text "+"
    In the second argument of ‘button_’, namely ‘[text "+"]’

Main.hs:46:43:
    Couldn't match type ‘[Char]’ with ‘JSString’
    Expected type: MisoString
      Actual type: [Char]
    In the first argument of ‘text’, namely ‘"-"’
    In the expression: text "-"
    In the second argument of ‘button_’, namely ‘[text "-"]’
```

**Comment by srid** [comment]
Applying the follow patch fixes it:

```diff
--- a/Main.hs
+++ b/Main.hs
@@ -41,7 +41,7 @@ updateModel SayHelloWorld m = m <# do
 -- | Constructs a virtual DOM from a model
 viewModel :: Model -> View Action
 viewModel x = div_ [] [
-   button_ [ onClick AddOne ] [ text "+" ]
+   button_ [ onClick AddOne ] [ text $ toMisoString "+" ]
  , text $ toMisoString (show x)
- , button_ [ onClick SubtractOne ] [ text "-" ]
+ , button_ [ onClick SubtractOne ] [ text $ toMisoString "-" ]
  ]
```

But is that in line with the 0.6.0.0 API?

**Comment by srid** [comment]
Just one last question, and then this issue can be closed!

```
sha256 = "07v2wrinnvkcmrmrav5xngybbms4scqhrhprbfqyak20snr4ir1q";
rev = "e2a3ac05f6b228c6060046fbdbf3d93c4232229c";
```

I understand the `rev` to refer to the git commit hash, but what is this `sha256` value and how to retrieve this for future latest releases?

**Comment by dmjio** [comment]
@srid ah thank you. I will update the docs to fix that example.

To get hash,

```bash
nix-prefetch-git https://github.com/dmjio/miso
Initialized empty Git repository in /private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/git-checkout-tmp-2ITGEzAn/miso/.git/
remote: Counting objects: 149, done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 149 (delta 23), reused 88 (delta 12), pack-reused 0
Receiving objects: 100% (149/149), 120.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (23/23), done.
From https://github.com/dmjio/miso
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is e2a3ac05f6b228c6060046fbdbf3d93c4232229c
path is /nix/store/yypcp3v5bnyfnh2nalilhklvca16pybv-miso
git human-readable version is -- none --
Commit date is 2017-08-04 11:38:52 -0700
hash is 07v2wrinnvkcmrmrav5xngybbms4scqhrhprbfqyak20snr4ir1q
{
  "url": "https://github.com/dmjio/miso",
  "rev": "e2a3ac05f6b228c6060046fbdbf3d93c4232229c",
  "date": "2017-08-04T11:38:52-07:00",
  "sha256": "07v2wrinnvkcmrmrav5xngybbms4scqhrhprbfqyak20snr4ir1q",
  "fetchSubmodules": true
}
```

You might need to install it with `nix-env -iA nix-prefetch-git -f '<nixpkgs>'`

Alternatively, just put the wrong hash, and nix will prompt you to enter the correct one.

**Comment by dmjio** [comment]
Re:example, try 
```bash
[nix-shell:~/Desktop/miso]$ cabal clean && cabal configure -fexamples --ghcjs && cabal build
```

**Comment by dmjio** [comment]
@srid, oh it needs `{-# LANGUAGE OverloadedStrings #-}`

**Comment by dmjio** [comment]
@srid sorry for the confusion, have applied this fix https://github.com/haskell-miso/miso/commit/36959c729888f7c0e204beba0e2d00a7b0b1323a

**Comment by dmjio** [comment]
Closing since fixed :) @srid

**Comment by srid** [comment]
@dmjio Thanks! It worked.

As for the hash, don't you think the README will need to be updated with the new rev/has on each release? Otherwise your (new) users of nix will end up using older versions ...

**Comment by dmjio** [comment]
@srid, yes it probably will. We should probably make a stub,

```

{ pkgs ? import <nixpkgs> {} }:
let
  result = import (pkgs.fetchFromGitHub {
    owner = "dmjio";
    repo = "miso";
    sha256 = "you hash goes here"; # example 07v2wrinnvkcmrmrav5xngybbms4scqhrhprbfqyak20snr4ir1q;
    rev = "your rev goes here"; # example "e2a3ac05f6b228c6060046fbdbf3d93c4232229c";
  }) {};
in pkgs.haskell.packages.ghcjs.callPackage ./app.nix {
  miso = result.miso-ghcjs;
}
```

This kind of descends into requiring us to provide more nix knowledge, we might need a "Just enough nix" section.

**Comment by srid** [comment]
I have been using NixOS on Linode since yesterday (primarily to develop with Miso, but maybe to make it my main dev machine) ... so I could provide some help with that. 

I was hoping there would be some sort of automatic way, maybe pull directly from GitHub release tag or some such thing without having to compute the hash .... I'll see ....

**Comment by srid** [comment]
But then I hear that to use cool things like intero+emacs they recommend Slack (and not nix) ... so perhaps I should look into a compound nix+Slack setup ... oh my, the possibilities ...

**Comment by dmjio** [comment]
:) they seem endless. Honestly, I like nix since most deps. are cached. With `stack` you have to build `ghcjs` from scratch. 
```
nix-shell -p 'haskell.packages.ghcjs.ghcWithPackages (p: with p; [ miso ])'
```
Can put you into a shell with `ghcjs` and `miso` w/o building anything, simply pulling from a cache. It's a huge win. Also, afaik, stack doesn't have a binary cache. Nixpkgs also just uses stackage LTS versions.
