### ISSUE TITLE
Removing ToView

### ISSUE THREAD

**Issue by cocreature** [haskell-miso/miso#239]
The `ToView` class seems to be completely unused (rightfully so in my opinion) so I would like to delete it, what do you think?

**Comment by dmjio** [comment]
`ToView` was meant to be a convenient way to convert your data into `View`. I guess there really aren't examples covering it. But here's what I had in mind in regards to usage.

```haskell
data Item 
  = Item 
  { name :: MisoString
  , id' :: Int 
  } deriving (Show, Eq)

instance ToView Item where
  toView Item {..} = li_ [ class_ $ ms (show id') ] [ text name ]

newtype Items 
  = Items [Item]
  deriving (Show, Eq)

instance ToView Items where
  toView = ul_ [] . map toView

newtype Model 
  = Model Items
  deriving (Show, Eq)

view Model {..} = div_ [] (toView items)
```

I kind of think it would be very convenient if a user knew exactly what `HTML` certain data would need to look like, and could use it anywhere via `ToView`, as opposed to having the resort to different function names everywhere. They could also `newtype` it to provide a different instances as well.

**Comment by cocreature** [comment]
Fair enough, then let’s keep it for now.

**Comment by dmjio** [comment]
Might not be bad to put this as an example in the haddocks either.
