### ISSUE TITLE
Nix: How to add new dependencies?

### ISSUE THREAD

**Issue by srid** [haskell-miso/miso#244]
This is mostly a documentation issue.

I'm using the Nix based setup (on NixOS). My app requires a new dependency. I did these:

1. Add the dependency to the cabal file
2. Add it to the .nix file
3. Run `nix-build`

In summary, I made these changes:

```diff
diff --git a/app.cabal b/app.cabal
index 8055e79..be3213d 100644
--- a/app.cabal
+++ b/app.cabal
@@ -7,5 +7,5 @@ cabal-version:       >=1.10

 executable app
   main-is:             Main.hs
-  build-depends:       base, miso
+  build-depends:       base, containers, miso
   default-language:    Haskell2010
diff --git a/app.nix b/app.nix
index 4271ff2..03009eb 100644
--- a/app.nix
+++ b/app.nix
@@ -5,7 +5,7 @@ mkDerivation {
   src = ./.;
   isLibrary = false;
   isExecutable = true;
-  executableHaskellDepends = [ base miso ];
+  executableHaskellDepends = [ base containers miso ];
   description = "Visualization in miso";
   license = stdenv.lib.licenses.unfree;
 }
```

Running `nix-build` produces this error:

```
error: undefined variable ‘containers’ at /home/srid/code/miso-viso/app.nix:8:37
```

`containers` is a Haskell package. What is the general instruction to add a new dependency in Miso?

Technically this might just be a Nix question (and thus not to belong here), however adding/ removing dependencies is covered in Elm documentation, and I figured that this is a such basic tasks before getting a non-trivial app running.

**Comment by srid** [comment]
Note: The `containers` dependency is for https://gist.github.com/dmjio/ad79a85d61601571bf2c1101c606dd72

**Comment by cocreature** [comment]
Your `app.nix` file probably starts with something like `{ mkDerivation, … }: …` The part before the colon is the argument set of your derivation. You need to add `containers` to that.

**Comment by cocreature** [comment]
In general, you can just run `cabal2nix` as described in the readme to generate this file.

**Comment by srid** [comment]
Ah, thanks. That worked!
