### ISSUE TITLE
Problem following Stack guide; ghcjs801 stack.yaml file doesn't work with Stack 1.3.2

### ISSUE THREAD

**Issue by ahri** [haskell-miso/miso#267]
I'm trying to follow the Stack guide in the README, with the following problems:

https://raw.githubusercontent.com/haskell-miso/miso/master/stack/ghcjs801/stack.yaml:

    Could not parse '/tmp/app/stack.yaml':
    Aeson exception:
    Error in $['extra-deps'][0]: failed to parse field 'extra-deps': (Invalid package identifier: "miso","miso")
    See http://docs.haskellstack.org/en/stable/yaml_configuration/

Is this a problem with my configuration? I'm currently running `stack setup` with https://raw.githubusercontent.com/haskell-miso/miso/master/stack/ghcjs7103/stack.yaml and that's building.

**Comment by cocreature** [comment]
The `stack.yaml` file is indeed incorrect but the `README.md` is not pointing to that and I think the stack.yaml file in the README should work. The problem with the `stack.yaml` you’re using is that the version of `miso` in `extra-deps` is missing. I’m not sure if these stack.yaml files are intended for hacking on `miso` or for users to copy to their own projects so I’m not sure if the right solution here is to add the version or to remove `miso` from `extra-deps`.

**Comment by ahri** [comment]
Using the stack.yaml in the `README` gives me this error:

    Could not parse '/tmp/app/stack.yaml':
    YAML parse exception at line 13, column 0,
    while scanning for the next token:
    found character that cannot start any token
    See http://docs.haskellstack.org/en/stable/yaml_configuration/

I wonder if I'm using an unsupported version of stack...

**Comment by ahri** [comment]
I've updated to stack 1.5.0 and get the same error with the `stack.yaml` from the `README`.

**Comment by dmjio** [comment]
@ahri yea, you'll want to specify the whole version.
```
packages:                                                                                                                                                                                                       
 - '.'                                                                                                                                                                                                          
extra-deps:                                                                                                                                                                                                     
 - miso-0.7.2.0 
```

I should probably just remove it altogether, this way the errors will be more meaningful.

@ahri can you paste the entire stack file you're using here?

**Comment by ahri** [comment]
I noticed when pasting the one from the `README` that it contains tabs; when properly spaced `stack` is happy with it.

**Comment by ahri** [comment]
Just to be clear, I was using:

    resolver: lts-6.20
    compiler: ghcjs-0.2.0.9006020_ghc-7.10.3
    compiler-check: match-exact

    packages:
     - '.'
    extra-deps:
     - miso-0.4.0.0

    setup-info:
      ghcjs:
        source:
          ghcjs-0.2.0.9006020_ghc-7.10.3:
    	 url: http://ghcjs.tolysz.org/lts-6.20-9006020.tar.gz
    	 sha1: a6cea90cd8121eee3afb201183c6e9bd6bacd94a

The last 2 lines contain tabs.

**Comment by dmjio** [comment]
@ahri care to make a PR? Now that you have the fix locally. Will gladly merge.
