### ISSUE TITLE
Nested elements act surprisingly with events

### ISSUE THREAD

**Issue by FPtje** [haskell-miso/miso#269]
This one really *looks* like intended behaviour at face value, but turns out to be surprising when you take a closer look. Please bear with me.

## How to reproduce

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
module Main where

import Miso
import Miso.String

type Model = ()

data Action
   = NoOp
   | SayHi

main :: IO ()
main = startApp App
    { initialAction = NoOp
    , model  = initialModel
    , update = updateModel
    , view   = viewModel
    , events = defaultEvents
    , subs   = []
    }

initialModel :: Model
initialModel = ()

updateModel :: Action -> Model -> Effect Action Model
updateModel action m = case action of
  NoOp -> noEff m
  SayHi -> m <# do
    putStrLn "HI!"
    pure NoOp

viewModel :: Model -> View Action
viewModel _ =
  a_
    [ onClick SayHi
    ]
    [ span_
      [ {-onClick NoOp-} ]
      [ text "(Clicking this won't work unless onClick NoOp is uncommented)" ]
    , text "(Clicking this will work)"
    ]
```

- Load the app
- Click the two texts
- Find that clicking the left text doesn't do anything, and the right text prints `HI!` in console

So far not *too* suprising, though I'd argue that an `onClick` event should apply to all children. Here's the kicker though:

- Uncomment the `{-onClick NoOp-}` bit in the `span_`.
- Reload the app
- Click the left text

I wouldn't expect the behaviour to change. It didn't do anything *without* `onClick`, and it's being told explicitly to do nothing *with* the `onClick`. Surprisingly, however, it prints `HI!`. That's weird.

## How Elm does it
Here's a comparable example in Elm:

```elm
import Html exposing (beginnerProgram, div, button, text)
import Html.Events exposing (onClick)

main =
  beginnerProgram { model = 0, view = view, update = update }

view model =
  Html.a
    [ onClick SayHi
    ]
    [ Html.span
      [ ]
      [ text "(Clicking this works in Elm) " ]
    , text "(Clicking this also works)"
    , text "  "
    , text (toString model)
    ]

type Msg = SayHi

update msg model =
  case msg of
    SayHi -> model + 1
```

Load in http://elm-lang.org/try to try

In Elm you can click either text to perform the `SayHi` action.

**Comment by dmjio** [comment]
When an event is fired in miso, we build up a stack from event.target back to body. We then reverse this stack (of pointers) and use it to index into the virtual DOM, to find the virtual DOM node that contains that pointer. From here we look up the name of the event and route it to a pure Haskell function. We then bubble up the parent tree and look for other event handlers with the same name and call them. This is a subtle bug where if an event handler does not exist, propagation ceases. It seems that the correct behaviour is to propagate the event handler regardless of whether or not we're listening for that event on the vDOM node that contains a reference that corresponds to event.target

**Comment by dmjio** [comment]
cc @FPtje https://github.com/haskell-miso/miso/pull/271

**Comment by dmjio** [comment]
https://github.com/haskell-miso/miso/commit/933721d2ee9238040a087457046588605a0b099e

**Comment by FPtje** [comment]
Fix confirmed. Awesome!

**Comment by dmjio** [comment]
Perfect 👌
