### ISSUE TITLE
Textarea cursor jumping around on input

### ISSUE THREAD

**Issue by FPtje** [haskell-miso/miso#272]
This one might be nasty. With a big enough application, the cursor in textareas starts becoming a little buggy. While typing, the cursor position might jump to the end of the input. I think it might be a race condition.

The example below may seem a bit forced, but I *am* experiencing this in a real world application.

## How to reproduce
Take the following code

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
module Main where

import Miso
import qualified Miso.String as MS


type Model = MS.MisoString

main :: IO ()
main = startApp App
    { initialAction = NoOp
    , model  = initialModel
    , update = updateModel
    , view   = viewModel
    , events = defaultEvents
    , subs   = []
    }


initialModel :: Model
initialModel = ""

data Action
   = NoOp
   | Update MS.MisoString

updateModel :: Action -> Model -> Effect Action Model
updateModel NoOp m = noEff m
updateModel (Update s) _ = noEff s

viewModel :: Model -> View Action
viewModel str = div_ [] $
    [ textarea_
      [ rows_ "10"
      , onInput Update
      , value_ str
      ]
      []
    ] <> replicate 1000 (p_ [] [text str])
```

- Load the page
- Type `aaa` in the textarea
- Place your cursor *before* the `aaa`
- Hold some other button to insert a bunch of letters before the `aaa`
- Watch the following happen:

https://youtu.be/Ta6pT72OTjE

What I *think* is happening:

The value of the textarea is stored in the model and goes back into the textarea with `value_ str`. I reckon there is some mechanism in Miso that stores and restores the cursor position when the textarea is updated. Perhaps the restoring of the cursor position is too slow, causing the cursor to jump hence and forth between the end of the input and where the user was typing.

## Some notes

- Note the `replicate 1000 (p_ [] [text str])`. Removing that seems to make the bug not happen. 
- If you can't reproduce it with `1000`, try increasing the number. Also, nice specs.

**Comment by FPtje** [comment]
Bug reproduced with Elm in [Elm Try](http://elm-lang.org/try):

```elm
import Html exposing (beginnerProgram, div, p, text, textarea)
import Html.Attributes exposing (value)
import Html.Events exposing (onInput)
import List exposing (repeat)

main =
  beginnerProgram { model = "", view = view, update = update }

view model =
  div []
  ([ textarea [ onInput Update, value model] []
  ] ++ (repeat 10000 (p [] [text model])))

type Msg = Update String

update msg model =
  case msg of
    Update str ->
      str
```

That makes this non-specific to Miso.

**Comment by FPtje** [comment]
I've found a workaround for this issue. It's hacky, but it works. Suggestions for better solutions are of course more than welcome.

```haskell
{-# language OverloadedStrings          #-}

module SmartTextarea where

import Prelude
import Miso hiding ( update )
import Miso.String ( MisoString )

-- | Internal state.
-- Refer to this in the parent model's type
data Model
   = Model
     { value     :: !MisoString -- ^ Updated on input
     , _setValue :: !MisoString -- ^ Set when value is changed externally
     }
     deriving (Eq)

-- | Initial model
-- Call when defining the initial model of the parent(s)
initialModel :: MisoString -> Model
initialModel str =
    Model
    { value         = str
    , _setValue     = str
    }

-- | Internal actions
data Action
   = SetValue !MisoString -- ^ First step of external value setting
   | ValueSet !MisoString -- ^ Second step of external value setting
   | Update   !MisoString -- ^ Updates the internal state on input

-- | Internal update
-- call from the update function(s) that embeds this component
update
    :: (Action -> action)
    -> Action
    -> Model
    -> Effect action Model
update onUpdate action m =
    case action of
      SetValue str ->
        m { value = str
          , _setValue = ""
          } <# pure (onUpdate $ ValueSet str)

      ValueSet str ->
        noEff $ m { _setValue = str }

      Update str ->
        noEff $ m { value = str }

-- | Function to set a value.
-- Use this from the parent's update function
setValue
    :: (Action -> action)
    -> MisoString
    -> Model
    -> Effect action Model
setValue onUpdate str = update onUpdate (SetValue str)


-- | View
-- Call this to embed the textarea in the view.
-- Requires the ability to execute `Action`s.
smartTextarea_
    :: Model
    -> (Action -> action)
    -> [Attribute action]
    -> [View action]
    -> View action
smartTextarea_ m onUpdate attrs =
    textarea_
      (attrs ++ ownAttrs)
  where
    ownAttrs =
        [ onInput $ onUpdate . Update
        , value_ $ _setValue m
        ]

```

The core issue lies in the fact that the `value_` is fed directly from the input. After every character typed in, a function is called to update the `textarea`'s value with whatever the value already is. This flow can be followed in the code in the OP: The `onInput Update` in the `View` is routed to a call to `update`, which sets the model to the input string. That model then is what defines the `value_` of the `textarea_` back in the view. Boom. Full circle 👌.

 The trick is not to that. Well, part of the trick anyway. The code above doesn't feed the `onInput` of the `textarea_` back into its `value_`. `onInput_` just updates a part of the model (the `value`) that isn't referred to in the view function. To update the `textarea_`'s text from other parts of the code there's the `_setValue` field in the model, prefixed with an underscore to indicate that you shouldn't use that value directly. Instead, there's a `setValue` function, which does some trickery for reasons explained below. 

Setting `_setValue` will cause the `textarea_` to discard the user's input and set the value to whatever you want it to. Except for when you change `_setValue` twice in a row with the same value. Onto the last part of the hack.

The `_setValue` part of the model only keeps track of what the value was last explicitly set to. To prevent the value of the `textarea_` looping back into itself, it isn't updated on input. Calling `setValue` twice with the same value would *not* reset the user's input, because the `textarea_`'s `value_` only changes when the model changes, and `_setValue` wouldn't have changed!

The solution for that is to first set `_setValue` to the empty string, to then immediately set it to the right value in the next round. The `setValue` function takes care of this.

**Comment by FPtje** [comment]
I just found out that this starts doing weird stuff when the `_setValue` of `Model` is set to the empty string. It makes the user unable to type anything in the textarea, since it would pretty much be set empty after every input.

**Comment by razvan-flavius-panda** [comment]
Is it necessary to use `MisoString` instead of `Text` for displaying  it in the UI?

**Comment by FPtje** [comment]
Miao functions use `MisoString` because it is an alias for `JSString`. It makes sense to use those because they are more performant.

**Comment by mtamc** [comment]
@dmjio Please re-open this issue, I am experiencing it reliably, cross-browser (Firefox, Chrome, Vivaldi), with a minimal example.

I'm not sure if @FPtje's hack still works as I haven't yet succeeded in adapting the code for today's Miso in a way that works.

Reproduction steps:

[1] Include a textarea in your page per my example code, or clone `miso-sampler` and replace `Main.hs` with the below

```hs
{-# LANGUAGE CPP #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Miso
import Miso.Html.Element as H
import Miso.Html.Event as E
import Miso.Lens

#ifdef WASM
#ifndef INTERACTIVE
foreign export javascript "hs_start" main :: IO ()
#endif
#endif

main :: IO ()
#ifdef INTERACTIVE
main = reload defaultEvents app
#else
main = startApp defaultEvents app
#endif

newtype Action
    = HandleTextareaInput MisoString
    deriving (Show, Eq)

app :: App MisoString Action
app = component "" updateModel viewModel

updateModel :: Action -> Effect parent MisoString Action
updateModel = \case
    HandleTextareaInput newVal ->
        this .= newVal

viewModel :: MisoString -> View MisoString Action
viewModel textareaVal =
    H.div_
        []
        [ H.h1_ [] ["🍜 Miso sampler"]
        , H.div_
            []
            [ H.textarea_ [E.onInput HandleTextareaInput] textareaVal
            ]
        ]
```

[2] In `miso-sampler`, run `nix develop .#wasm --command bash -c 'make && make serve'` or `nix develop .#wasm --command bash -c 'make watch'`

[3] Type a bit in the textarea, then move the cursor somewhere that's not the end of the textarea, and start typing fast (maybe typing not just one character repeated will help reproducing)

Video demonstration:

https://github.com/user-attachments/assets/63cf50d1-a9ad-4a68-83b2-6d22628cfdfa

**Comment by dmjio** [comment]
This is a known race condition.

The changed value of the input area is being set as the value on the model, and then the value of the model back to the input area. 

It's best not to set `textAreaVal` in the `view` function. Only set the changed value on the model in `update`.

**Comment by mtamc** [comment]
Following the conversation Matrix, I'm saving this link here for future reference/investigation. It contains some information on how Elm dealt with this bug. https://github.com/elm/virtual-dom/issues/138#issuecomment-648110911

Other thread with potential fixes and workarounds: https://github.com/elm/html/issues/105
