### ISSUE TITLE
Snake

### ISSUE THREAD

**Issue by dmjio** [haskell-miso/miso#281]
Would be a nice example. Should be a simple port from Elm.
https://github.com/theburningmonk/elm-snake

**Comment by lbonn** [comment]
Here is a version: https://github.com/lbonn/miso-snake.

I tried to keep the same simple model and code structure but used the SVG api instead of a canvas (as well as some Haskell-specific idioms). As a result, it is not a pixel-perfect clone.

I'll try to supply a playable link soon.

**Comment by dmjio** [comment]
@lbonn less than pixel perfect is fine with me :)

**Comment by dmjio** [comment]
Thanks @lbonn :)
