### ISSUE TITLE
Miso tries to set read-only properties instead of using `setAttribute`

### ISSUE THREAD

**Issue by cocreature** [haskell-miso/miso#283]
Currently `miso` checks if an attribute exists as a property and if so it tries to set that property, if not it falls back to `setAttribute`. However some properties, e.g., the `form` attribute on [HTMLButtonElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement) are read only and cannot be set via the JS property. At least `form` *can* however be set via `setAttribute`. While I’ve only seen this problem with `form` I doubt that this is the only property affected by this. It would thus be nice to find a general solution for this instead of adding a bunch of exceptional cases.

**Comment by dmjio** [comment]
Yea, this does seem problematic. I've been told that `form` and `list` are the only two exceptions. 

So, if you can make a PR on https://github.com/haskell-miso/miso/blob/master/jsbits/diff.js#L83 that looks like:
```javascript
} else if (c in node && c !== "list" && c !== "form") { 
```
same for line `102`

**Comment by dmjio** [comment]
55e5927a21fc4ff3504e0f861c35c342990a3989

**Comment by cocreature** [comment]
Thanks for the fix!

**Comment by dmjio** [comment]
np 🍻
