### ISSUE TITLE
Subscription for periodic ticks

### ISSUE THREAD

**Issue by lbonn** [haskell-miso/miso#284]
Like Elm's [every](http://package.elm-lang.org/packages/elm-lang/core/latest/Time#every), based on `setInterval`.

It doesn't look difficult to add and would be especially nice for tutorials and simple examples.

**Comment by dmjio** [comment]
```haskell
every :: Int -> (Double -> action) -> Sub action model
every n f _ = \sink -> forever $ do
  threadDelay (secs n)
  sink (f =<< Time <$> now)
```

`threadDelay` is equivalent to `setInterval`

**Comment by lbonn** [comment]
Thanks, I guess I should have asked on irc first.

**Comment by dmjio** [comment]
@lbonn, it's no problem, we have a slack too. Do you think a `Miso.Subscription.Time` module would be necessary?

**Comment by lbonn** [comment]
It probably depends if you'd prefer to keep a really small (but composable) base library. I suppose your goal is not to do an Elm clone anyway...

As a newcomer, perhaps I would have appreciated seeing it somewhere in the docs/tutorial as an example. Another radical approach: including it in the `Sub` type's haddock.

**Comment by dmjio** [comment]
@lbonn I'll be sure to add this to the docs when they are written. Closing due to completion.
