### ISSUE TITLE
Websockets: non-working state after socket closes

### ISSUE THREAD

**Issue by FPtje** [haskell-miso/miso#288]
# How to reproduce

- Take the [websocket](https://github.com/haskell-miso/miso#websocket) example.
- Change the URL to some websocket server that sends one message and then immediately closes the socket

# Expected behaviour
- That one message is printed
- The web socket is closed
- [This here logic](https://github.com/haskell-miso/miso/blob/master/ghcjs-src/Miso/Subscription/WebSocket.hs#L74-L80) re-opens the socket within three seconds
- repeat step 1

One could argue that a neatly closed socket shouldn't be re-opened like that, but that's not the point of this issue.

# Actual behaviour
- That one message is printed
- The web socket is closed
- The socket is re-opened within three seconds
- No messages about this socket arrive to the application

# Why it happens
The `onOpen`, `onMessage`, `onClose` and `onError` handlers [here](https://github.com/haskell-miso/miso/blob/master/ghcjs-src/Miso/Subscription/WebSocket.hs#L81-L97) refer to the `socket` defined on [line 71](https://github.com/haskell-miso/miso/blob/master/ghcjs-src/Miso/Subscription/WebSocket.hs#L71). That's the *old* socket, not the *new* `socket` created on [line 80](https://github.com/haskell-miso/miso/blob/master/ghcjs-src/Miso/Subscription/WebSocket.hs#L80) when the connection closes.

# Solution
Not sure, but go in recursion on line 79-80 instead of rewriting the `IORef`?

I haven't made a PR for this because I'm not sure whether recreating the socket on close is *always* a good idea. I reckon it's a good idea to reconnect when the socket closed due to an error, but not when it's closed properly.

# Simple example server
Not full code, sorry for that

```haskell
import qualified "wai" Network.Wai as Wai
import qualified "wai-websockets" Network.Wai.Handler.WebSockets as WebSockets
import qualified "websockets" Network.WebSockets.Connection as WebSockets

main = WebSockets.websocketsOr opts serverApp nonSocket
  where
    serverApp :: WebSockets.PendingConnection -> IO ()
    serverApp pconn = do
            conn <- WebSockets.acceptRequest pconn
            WebSockets.sendTextData conn ("\"AAA\"" :: T.Text)

    nonSocket _req respond =
            respond $ Wai.responseLBS
                Http.notAcceptable406
                [("Content-Type", "text/plain")]
                "This is a websocket route. Connect to it using websockets."

    opts = WebSockets.ConnectionOptions $ pure ()
```

**Comment by dmjio** [comment]
@FPtje, great work again :) 

Regarding,
> I haven't made a PR for this because I'm not sure whether recreating the socket on close is always a good idea.

It might be best if we only re-open the socket if the error code *is* erroneous. For example, if the close code was a `1000`, we could just simply not recurse and keep the socket in closed state.
